POST http://127.0.0.1:8002/api/v1/notifications
Accept: application/json
Content-Type: application/json

{

    "client_info": {
        "client_name": "Kirill",
        "phone": "+71111111111",
        "email": "krllbobrov@gmail.com"
    },
    "status_info": {
        "order_name": "Shoes",
        "status": "accepted",
        "current_location": "Moscow",
        "updated_at": "2024-04-11T14:04:40.000000Z"

}
}


