openapi: "3.0.0"
info:
  version: 1.0.0
  title: NotificationSender API
  contact:
    name: API Support
    url: https://non.existing/contacts
    email: mail@miet.ru
  description: NotificationSender responsible for sending email (mb sms) notifications about delivery status change to client.
servers:
  - url: /api/v1
    description: NotificationSender service.
tags:
  - name: statusChangedNotification
    description: Order deliveries status changed related actions tag
paths:
  /notifications:
    post:
      summary: Send request for notification
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\NotificationsController@post'
      x-lg-route-name: 'postNotification'
      x-lg-skip-request-generation: true
      description: Send request for notification about delivery status changed
      operationId: postStatusChangedNotification
      tags:
        - statusChangedNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Notification"
      responses:
        '201':
          description: Notification request successfully sent
        '400':
          description: Bad request received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        'default':
          description: Unexpected status code received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    ClientInfo:
      type: object
      required:
        - client_name
        - phone
        - email
      properties:
        client_name:
          type: string
        phone:
          type: string
          format: phone
          pattern: 7\d{10}
        email:
          type: string
          format: email
    StatusInfo:
      type: object
      required:
        - order_name
        - status
        - current_location
        - updated_at
      properties:
        order_name:
          type: string
        status:
          type: string
          enum:
            - accepted
            - processing
            - in_transit
            - delivered
            - picked_up
        current_location:
          type: string
        updated_at:
          type: string
          format: date-time
    Notification:
      type: object
      required:
        - client_info
        - status_info
      properties:
        client_info:
          $ref: '#/components/schemas/ClientInfo'
        status_info:
          $ref: '#/components/schemas/StatusInfo'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
